name: narratrivia
description: "App di trivia narrativa con domande su anime, manga, videogiochi, serie TV, film e libri."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.4
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_crashlytics: ^3.4.8

  # Gestione stato
  provider: ^6.1.1

  # Storage locale
  shared_preferences: ^2.2.2

  # Database
  sqflite: ^2.3.0
  path: ^1.8.3

  # Internazionalizzazione
  intl: 0.20.2

  # Audio
  audioplayers: ^6.5.0

  # UI
  cupertino_icons: ^1.0.6
  change_app_package_name: ^1.5.0

  # Networking (utile per Firebase)
  http: ^1.1.2

  # Logging (utile per debug Firebase)
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: false

  assets:
    - assets/images/backgrounds/
    - assets/images/buttons/
    - assets/images/icons/
    - assets/sounds/
    - assets/data/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf